# Generated by Django 6.0.4 on 2026-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('source_node_id', models.CharField(max_length=1024)),
                ('target_node_id', models.CharField(max_length=1024)),
                ('relation', models.CharField(default='imports', max_length=64)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id', 'source_node_id'], name='rag_codeedg_project_796d47_idx'), models.Index(fields=['project_id', 'target_node_id'], name='rag_codeedg_project_152291_idx')],
                'unique_together': {('project_id', 'source_node_id', 'target_node_id', 'relation')},
            },
        ),
        migrations.CreateModel(
            name='CodeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('node_id', models.CharField(max_length=1024)),
                ('node_type', models.CharField(default='file', max_length=64)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
                ('file_path', models.CharField(blank=True, default='', max_length=2048)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id', 'node_type'], name='rag_codenod_project_848bf8_idx')],
                'unique_together': {('project_id', 'node_id')},
            },
        ),
    ]
