# Generated by Django 6.0.4 on 2026-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('source_dir', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('documents_collected', models.PositiveIntegerField(default=0)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('vectors_upserted', models.PositiveIntegerField(default=0)),
                ('graph_nodes', models.PositiveIntegerField(default=0)),
                ('graph_edges', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['project_id', 'status'], name='rag_indexin_project_414a93_idx'), models.Index(fields=['queued_at'], name='rag_indexin_queued__43f20d_idx')],
            },
        ),
    ]
