# Generated by Django 6.0.4 on 2026-05-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_indexingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeedge',
            name='indexing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_edges', to='rag.indexingjob'),
        ),
        migrations.AddField(
            model_name='codenode',
            name='indexing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_nodes', to='rag.indexingjob'),
        ),
    ]
